Remove the testable library (and some typescript clean up)
axsy-dev/react-native-form-generator pull request #24
Opened 2022-07-07 18:49 UTC by scottpage1317

- Replaces any components from the testable library with their underlying components
- Replaces TestPathSegment with a `tidRoot` which is defined in Form.js to the parent elements testID if `hasTestableWrappers` is set or `Element[index]` if's not.
- Fixes some typescript issues in `InputComponent` - I've tried to be as careful as possible to not change the behaviour of the field

I've tested this using flows which contain all the elements we support on Android and iOS (I'll keep this a draft until I test on Windows too), but I'm aware that doesn't cover all of the components in RNFG (the Switch and Link components for example) so am keen to get any suggestions for other places to test

2022-09-12 09:20 UTC, scottpage1317 commented
@GuyChatfield this is the PR which I think should be tested on Windows - how did you say I could test it without a working windows environment?

2022-10-12 13:06 UTC, GuyChatfield approved these changes
looks good to me 👍

2022-10-12 13:26 UTC, colincarter requested changes
Thanks for the improvements @scottpage1317 .  Few changes to look at.

2022-10-12 13:26 UTC, colincarter commented on src/Form.js
> +      <View testID={`Form`} style={this.props.style}>
This `testId={'Form'}` could be replaced with `testID="Form"`

2022-10-12 13:26 UTC, colincarter commented on src/lib/DatePickerComponent.android.js
> +        ? `Value/${this.state.date?.getTime()}`
`'Value/' + this.state.date` as a string of length > 0 will always evaluate to truthy, so the "Unknown" clause will never be.  ditto the ones below

2022-10-12 13:26 UTC, colincarter commented on src/lib/Field.js
> +        <TouchableOpacity onPress={this.props.onPress} testID={`TapTarget`}>
See above for the testIDs

2022-10-12 13:26 UTC, colincarter commented on src/lib/PickerComponent.ios.js
> +                testID={`PickerItem/${idx}`}
Is there some formatting issues here with the extra indentation?  Is prettier running?

2022-10-12 13:26 UTC, colincarter commented on src/lib/TimePickerComponent.android.js
> +      <Text testID={`Label`} style={this.props.placeholderStyle}>
`Text` hasn't been imported here

2022-10-12 13:26 UTC, colincarter commented on src/lib/DatePickerComponent.android.js
> +let { View, Text } = require("react-native");
Could you use `import {View, Text} from "react-native"` here?

2022-10-12 13:26 UTC, colincarter commented on src/lib/DatePickerComponent.windows.js
> +let { View, Text } = require("react-native");
See above

2022-10-12 13:26 UTC, colincarter commented on src/lib/LinkComponent.js
>  let { View, StyleSheet, Text, ViewPropTypes } = require("react-native");
See above

2022-10-14 14:22 UTC, colincarter approved these changes
Thanks, looks good now.

2022-10-14 14:22 UTC, merged